language: java
sudo: false

jdk:
  - oraclejdk8

install: true
script: ./travis.sh
env:
  - TEST=ci



matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
  webhooks:
    - secure: "1u0hicbRywUTYGzKPq7awMK0taYj76nnul0UWTsfor/qEyE1ozHiMUj5u/0sXjK81q/uDotaX2S2M/s8cxV3LXzdUiPWOiXE1h+r7o/Sjm7NoOrsLSyHtFpquWcgJHRQTLay4hAwPH5yUAjuyw5gan+LeUet9ljdQ3TtuZDOS3w="
